### ISSUE TITLE
Possibility to store auth-token on server and also check for it?

### ISSUE THREAD

**Issue by Adevien** [jerson/pgrok#14]
Is it possible to store auth-token on server and also check for it?

**Comment by jerson** [comment]
Hi @Adevien thanks for the question, no currently we dont support that, remember that this is a fork of an older version of ngrok so maybe someone else already did that

**Comment by arthurkay** [comment]
Hey @jerson this seems like a cool feature, I can spare some time to develop it. But I've noticed the project hasn't gotten any update in almost a year now. Is it still actively maintained? Let me know if you need help.

**Comment by jerson** [comment]
Hi @arthurkay yeah this repo is not mantained, please feel free to fork and add New features
