### ISSUE TITLE
it will not connecting

### ISSUE THREAD

**Issue by yasmijn-vels** [jerson/pgrok#15]
the tunnel just won't connect

![image](https://user-images.githubusercontent.com/93641365/140021815-e77830d7-1857-4f1a-831f-c3232c780637.png)

**Comment by FilipeCapela98** [comment]
Same thing happening with me, tunnel status will say connecting and then starts "reconnecting"

**Comment by AndreTeixeira1998** [comment]
having the same issue. help

**Comment by dinccey** [comment]
Windows? Could be a firewall issue.

**Comment by yasmijn-vels** [comment]
> Windows? Could be a firewall issue.

no i have the firewall off

**Comment by dinccey** [comment]
> > Windows? Could be a firewall issue.
> 
> no i have the firewall off

I can't replicate the problem, works fine for me on windows and linux.

**Comment by jerson** [comment]
Hi @yasmijn-vels seems a firewall issue to me too, i have faced similar issues on windows and for me didnt work because in my job they block some ports and that is needed in order to make it work. so i dont think there are anything i can do, unless this issue is related to a different thing

**Comment by yasmijn-vels** [comment]
hi @jerson explain to me then! why does a ngrok tunnel work on my computer without any problems?

**Comment by jerson** [comment]
thanks for the fast answer @yasmijn-vels probably that is a different scenario, im gonna test on windows, can you tell me which exact windows version do you have and what dns are you using also which pgrok version are you using

**Comment by yasmijn-vels** [comment]
hi @jerson i'm using windows server 2019

**Comment by anand-010** [comment]
I have the same problem when using old windows builds please use latest builds from the release section.

**Comment by jerson** [comment]
I havent tested in windows server 2019 and i dont have way to test here, you can try with latest version, and if doesnt work you can try with a custom server, maybe is something related with the domain ejemplo.me im using a server located in france and using letsencrypt for TLS

**Comment by The-Chosen-Sausage** [comment]
> hi @jerson i'm using windows server 2019 and the pgrok verion is the latest version

Maybe you're using the wrong server.
[https://www.proxy.jetzt/](url)
This server wont work. Just leave the config file empty.
