### ISSUE TITLE
Not work with custom server (docker).

### ISSUE THREAD

**Issue by anand-010** [jerson/pgrok#18]
I have hosted the docker image on aws and opened inbound ports 80,443,4443 The server seems to be working.
`pgrok                                                                                                   (Ctrl+C to quit)                                                                                                                        Tunnel Status                 online                                                                                    Version                       3.0/3.0                                                                                   Forwarding                    https://lexsmarthome.com -> 127.0.0.1:8000                                                Forwarding                    http://lexsmarthome.com -> 127.0.0.1:8000                                                 Web Interface                 http://127.0.0.1:4040                                                                     # Conn                        0                                                                                         Avg Conn Time                 0.00ms   `

But when I tried to connect to the http address it shows "Tunnel lexsmarthome.com not found".
This is the command i am used.
`pgrok.exe -hostname="lexsmarthome.com" -subdomain=example 8000`
But when i tried to replace my domain with this.
`pgrok.exe -hostname="ejemplo.me" -subdomain=example 8000`
It hosts my page on the domain without the subdomain.
Please help me.
I am expecting something like this http://example.lexsmarthome.com.
I have already setup the wildcard domain.

**Comment by dinccey** [comment]
Try running it like this:
`pgrok.exe -hostname="example.lexsmarthome.com" -proto=http+https 8000`
