### ISSUE TITLE
Is there C implemented version?

### ISSUE THREAD

**Issue by tufeigunchu** [jerson/pgrok#19]
I want to run on openwrt router with 64M memory. I think go version is too heavy. Just wonder if there is C version so that it eats less memory

**Comment by MislavJancic** [comment]
There isn't any. 64M is a really small amount of memory, I can't imagine it's paired with an adequate processor either. You can try it though, hopefully the garbage collector will free up enough memory.

**Comment by jerson** [comment]
unfortunately there are no C version, we are just trying to support the existing old ngrok version with a fork so there are no plans to create a C version of this
