### ISSUE TITLE
Docker Hub image is not auto-built

### ISSUE THREAD

**Issue by synchrone** [jerson/pgrok#2]
Hello and thank you for this project,

since it requires access to the TLS certificate private keys to function, I find it problematic that [Docker Hub image](https://hub.docker.com/r/jerson/pgrok) is pushed manually, and not auto-built by docker hub from this repository.

Is there a reason the build process needs to happen outside of public view?

**Comment by synchrone** [comment]
additionally, github releases are also built with a private GH action `jerson/goreleaser` ?

**Comment by jerson** [comment]
hi @synchrone thanks for report this issue, I enabled automatic docker hub build again, im not sure why i disabled in the past, maybe because some news of docker hub about pricing, but i read and seems like its free for public repos

**Comment by jerson** [comment]
also for build im using a docker image 

jerson/goreleaser

which contains a custom go version, i think that we can change that if you want the docker file is just this, all my custom docker files are in gitlab, i think i can create a mirror repo in github to more transparency

```
FROM jerson/go:1.13

LABEL maintainer="jeral17@gmail.com"

RUN git clone https://github.com/goreleaser/goreleaser && \
    cd goreleaser && \
    git checkout v0.118.2 && \
    go get ./... && \
    go build -o goreleaser . && \
    mv goreleaser /usr/local/bin/goreleaser

COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by jerson** [comment]
in addition to this my golang docker file is this
```dockerfile
FROM golang:1.13-alpine

LABEL maintainer="jeral17@gmail.com"

ENV GOPROXY https://proxy.golang.org,direct

ENV GOPATH /srv/go
WORKDIR ${GOPATH}

RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    echo "@community http://nl.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories

RUN apk add --no-cache binutils make supervisor openssh gcc musl-dev build-base
RUN apk add --no-cache zip unzip git mercurial curl rpm docker-cli bash
RUN apk add --no-cache jpegoptim@community pngquant@community upx@community
RUN apk add --no-cache ca-certificates && update-ca-certificates 

ENV SUPERVISORD="/etc/supervisor.d"
RUN mkdir -p ${SUPERVISORD}

RUN mkdir -p /var/log/go/ && \
    mkdir -p ${GOPATH}/src/ && \
    mkdir -p ${GOPATH}/bin/

ENV PATH ${GOPATH}/bin:/usr/local/go/bin:$PATH

RUN go get -u golang.org/x/lint/golint && \
    go get -u github.com/golang/dep/cmd/dep && \
    go get -u github.com/gobuffalo/packr/v2/packr2 && \
    go get -u github.com/jteeuwen/go-bindata/go-bindata && \
    go get -u github.com/markbates/pkger/cmd/pkger

COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by synchrone** [comment]
I was just about to ask what's happening in https://hub.docker.com/r/jerson/base, that is used as FROM in this Dockerfile

also yes, jerson/go is non-standard

**Comment by jerson** [comment]
yeah base is just an alpine with ca certs, probably we can create a PR to use just official docker images to provide a better binary

```
FROM alpine:3.11

LABEL maintainer="jeral17@gmail.com"

RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    echo "@community http://nl.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories

RUN apk add --no-cache ca-certificates && update-ca-certificates
RUN apk add --no-cache tzdata

ENV TZ America/Los_Angeles

COPY entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by synchrone** [comment]
I understand this may be a non trivial amount of work to making all the relevant builder/publisher infrastructure open, but I hope you can see how users may be uncomfortable trusting opaque binaries with TLS private keys for their domain certs.

**Comment by jerson** [comment]
yeah, feel free to scan every image, but you are right, im going to change all by official docker images

https://microbadger.com/images/jerson/base

**Comment by jerson** [comment]
hi @synchrone  i just updated dockerfile and github action file

https://github.com/jerson/pgrok/blob/master/.github/workflows/release.yml

https://github.com/jerson/pgrok/blob/master/Dockerfile

i think that now is more clear, and probably we can only use goreleaser to build multiarch docker images also, but for now i think its ok

https://github.com/jerson/pgrok/releases/tag/v3.2.2

is the first release using this new config,

for now im going to close this ticket but feel free to reopen if you need

**Comment by jerson** [comment]
with latest changes we depends only on github actions to build docker images

https://github.com/jerson/pgrok/blob/master/.github/workflows/docker.yml

and generate well tagged images with multi arch support

https://hub.docker.com/r/jerson/pgrok/tags?page=1&ordering=last_updated

also docker images can be used from github registry

https://github.com/users/jerson/packages/container/package/pgrok

thanks for you suggestions i think that now we have a more convenient library :D
