### ISSUE TITLE
Terminating free ejemplo.me server

### ISSUE THREAD

**Issue by jerson** [jerson/pgrok#20]
sadly someone is using the service to expose malware, the only possible solution for me is to terminate ejemplo.me, you can still expose your own server using readme tutorial.

`[PL-2738190] Phishing attack(s) hosted on: trending.ejemplo.me During an investigation of fraud, we discovered a compromised website (trending.ejemplo.me) that is being used to attack our client and their customers. In addition to the website owner, we have addressed this report to the responsible authoritative providers who have the ability to disable the malicious content in question. Based on your relationship to the content in question, please see our specific request below. This threat has been active for at least 0.4 hours. http://trending.ejemplo.me/login.html http://trending.ejemplo.me/ First detection of malicious activity: 12-06-2021 20:17:12 UTC Most recent observation of malicious activity: 12-06-2021 20:40:54 UTC Associated IP Addresses: 51.15.103.235 === HOSTING PROVIDER === If you agree that this is malicious, we kindly request that you take steps to have the content removed as soon as possible. It is highly likely that the intruder who set up this phishing content has also left additional fraudulent material on this server such as illegitimate access points. === WEBSITE OWNER === We recommend taking the following actions to secure the web site and prevent the attackers from returning: - Update your web applications including CMS, blog, ecommerce, and other applications (and all add-on modules/components/plugins). - Search all of your web directories for suspicious files as attackers commonly leave backdoors. - Scan the computer from which you login to your web hosting control panel or ftp server with anti-virus software. - Change your web hosting provider if this is an ongoing issue. If your provider has disabled your account because of this incident, you must coordinate a resolution with them directly as PhishLabs has no control over this aspect. If we have contacted you in error, or if there is a better way for us to report this incident, please let us know so that we may continue our investigation. We are grateful for your assistance. Kind regards, SOC Team PhishLabs Security Operations 12023866001 Available 24/7 [PL-2738190]`

**Comment by dwarfpuzzles** [comment]
Rest in peace.
Forever miss.

**Comment by MislavJancic** [comment]
Some people -_-

**Comment by alisonreis1991** [comment]
usava bastante o pgrok aqui em casa, tem como você ativalo novamente?

**Comment by Alex-idk** [comment]
@jerson Quick question, can I run pgrok server without a domain if im just going to be using TCP tunnels?

**Comment by jerson** [comment]
I just updated docs with more details about self hosting
https://github.com/jerson/pgrok/blob/master/docs/SELFHOSTING.md

and about @Alex-idk question, I havent tested using only tcp so, im not sure about that but probably you can use https://github.com/fatedier/frp which has a better implementation for expose ports

**Comment by dwarfpuzzles** [comment]
Does ejemplo.me support TCP still?

**Comment by jerson** [comment]
@dwarfpuzzles no, for now the service is down since i can not avoid that someone can expose malware using ports too,

**Comment by dwarfpuzzles** [comment]
ngrok has this problem as well

**Comment by jerson** [comment]
Actually you can protect you pgrok instance using client certificates and CA, doc was included in Protect you client(pgrok) to server(pgrokd) connection with a CA

Section

**Comment by SumirekoUsami** [comment]
Huh, a bruh moment indeed. It's sad to see this service being shut down, it truly was a very convenient way to share localhosted websites to the internet without configuration :( \
I think that now, without a public `pgrokd` instance, people who don't have their own server with static IPs will not be able to use pgrok as before? If that's the case, would you consider changing the default server to another one, hosted by someone, who has the will (and time and resources) to take care of malware issues (and others)? :D \
I personally think that using pgrok without selfhosting is a very popular usage case and that's why I believe this issue is important. My hosting provider also happens to forward all copyright/fishing claims to it's clients before taking any action too, so... I suppose I can host a public pgrok instance, yay.

**Comment by Alex-idk** [comment]
I mean pgrok isn't the only thing to forward localhost things with there is ngrok, localhost.run, pagekite.net, or a plain old ssh port forwarding to a vps

**Comment by alisonreis1991** [comment]
Jerson, how can i make pgrok work on my pc, could you make a video showing how i can make it work on my computer?
