### ISSUE TITLE
Is support for UDP planned?

### ISSUE THREAD

**Issue by NhProGamer** [jerson/pgrok#22]
all is in the title

**Comment by ghost** [comment]
Couple months ago I wanted to add proximity chat support on a temporary minecraft server, but it was using UDP...

So I actually need UDP too

**Comment by NhProGamer** [comment]
@Tarocafe je te recommande d'utiliser [frp](https://github.com/fatedier/frp), tu peut config le client avec une simple page web en local, le serveur est protégé par un "simple" mot de passe, je te consille d'en générer un assez long. 
De plus avec frp tu peut surveiller la conso de la bande passante pgrok plus est orienté développement web, je cois qu' il n'y aura jamais de support pour l'UDP. Je te passe mon discord si tu veut plus d'aide </NнPяo>🗕 🗗 🗙#2800

**Comment by ghost** [comment]
@NhProGamer Je testerais frp, mais pour l'instant je vais rester sur pgrok

En fait avant d'envoyer mon message il y a 4 jours, j'avais oublié que mon hébergeur n'autorisais pas UDP (c'est censé faire de l'hébergement web et non pas de l'hebergement de VPS).

Donc dans tout les cas j'ai besoin d'un VPS... ou de tout simplement ouvrir mes ports, ce que je n'ai pas très envie de faire.

**Comment by NhProGamer** [comment]
stv un tout petit vps (1v core; 512mb ram 10Go ssd) tu en as un a 1.20€ chez ionos
