### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by gedw99** [jerson/pgrok#23]
Hey @jerson 

great to see pgrok alive .

i am going to create a gui using gio which I use everyday .  Its 100% golang and it’s easy to make a taskbar app for windows , Mac and Linux with it .

https://github.com/gioui

i got GRPC and GRPC- Web as well as Flat Buffers , and so offers working with it.

mit can also work with react because you can just compile the golang client to wasm and bridge to react . We can discuss if your interested as I know to doing stuff like this in your repos.

I was also wondering if pgrok could be a vpn for users ? So you can place servers where you want , connect to them and pgrok will allow you to connect from your devices to the internet via your pgrok servers .

**Comment by arthurkay** [comment]
Hey @gedw99 I don't think this project is actively maintained anymore. However, I have my own fork of this project that I've been working on, so if interested. Feel free to reach out.
