### ISSUE TITLE
Never connecting.

### ISSUE THREAD

**Issue by TeaSpillStudios** [jerson/pgrok#26]
I've tired on arch linux (x64) and raspberry pi os (arm64) and neither work, they will say connecting for a couple seconds then go onto reconnecting, my ~/.pgrok.com is empty as I was told to leave it empty as the proxy site is not available anymore so it should be left empty.

![image](https://user-images.githubusercontent.com/57747851/178366350-e7ca380c-9469-4029-bb58-5ae01440cb59.png)

Any help would be greatly appreciated!

**Comment by jerson** [comment]
hi @TeaSpillStudios sorry but that service was terminated
see: https://github.com/jerson/pgrok/issues/20
