### ISSUE TITLE
Authenticity of proxy.jetzt?

### ISSUE THREAD

**Issue by TeaSpillStudios** [jerson/pgrok#28]
I noticed when searching pgrok, another website called proxy.jetzt is recommended, which seems a lot like the ejemplo.me service. 

It says to put this:

```
server_addr: ixo-pgrok01.in.ixolit.com:4443
trust_host_root_certs: true
```

It seems `ixolit.com` is an ecommerce website, so I have no idea how it is set up, maybe the website allows you to have shell access.

I was wondering if this was even made by the project pgrok or if it was just something someone was hosting. I was also wondering if you would know if it is safe or not.

Thanks for your time reading this

**Comment by jerson** [comment]
Hi, someone else did that, wasn't me, I can't guarante anything, its recommended to deploy your own pgrok your server instead

**Comment by TeaSpillStudios** [comment]
Okay, I’ll try and self host a server if I can and not use this. Hopefully I can stop using ngrok. Thanks.
