### ISSUE TITLE
How can I get the IP address of the client?

### ISSUE THREAD

**Issue by programmeruser2** [jerson/pgrok#3]
How can I get the IP address of the client e.g. the IP that the server receives when you visit your website in the browser?

**Comment by jerson** [comment]
hi @programmeruser2 thanks for you question, you can do that with javascript in your exposed client if you want,
https://stackoverflow.com/a/35123097/757396

i think that grab client ips is not the purpose of this library, but you create a fork if you feel necesary

**Comment by programmeruser2** [comment]
> i think that grab client ips is not the purpose of this library
I don't quite understand your answer, but it would be nice to add headers like `X-Forwarded-For` and `X-Forwarded-Proto` for client information that isn't accessible because of the proxy.

**Comment by jerson** [comment]
ohh i see what you mean, sorry about my first answer, im going to research about forward headers, i didnt used before for pgrok, so probably is a code change in proxy as you mentioned
