### ISSUE TITLE
How can I running this on Android ( Termux )

### ISSUE THREAD

**Issue by songoten28** [jerson/pgrok#4]
I already download ARM64 or even build it by myself. Seem it not working

**Comment by songoten28** [comment]
Im build wrong cpu architecture. Sorry about this accident

**Comment by jerson** [comment]
hi @songoten28 thanks for report the issue, for out next build im adding android binaries to releases

https://github.com/jerson/pgrok/commit/7a9e9f632c4c423273142dafaa49ea1923dfa82d

is building now but should be available here:
https://github.com/jerson/pgrok/releases/tag/v3.2.4

**Comment by jerson** [comment]
https://github.com/jerson/pgrok/releases/download/v3.2.4/pgrok_3.2.4_android_arm64.tar.gz

finally works :D, it seems that go 1.16 doesn't support android arm7 anymore, but I don't think it's necessary to support it anymore.

**Comment by songoten28** [comment]
Hm 

> https://github.com/jerson/pgrok/releases/download/v3.2.4/pgrok_3.2.4_android_arm64.tar.gz
> 
> finally works :D, it seems that go 1.16 doesn't support android arm7 anymore, but I don't think it's necessary to support it anymore.

Some devices like Android TV still using armv7a for sure. Better Pgrok should support for them

**Comment by jerson** [comment]
thanks I didn't know that, I'm going to do some tests to see if I can support it with another github actions maybe.
