### ISSUE TITLE
Memory leak and client crash when downloading files over pgrok

### ISSUE THREAD

**Issue by dinccey** [jerson/pgrok#6]
I tried to download files from my nextcloud and it appears that using pgrok to bypass NAT is not so great for a scenario where you need to download files. Memory use of pgrok starts going up like crazy using what seems to be more than the file that's being downlaoded. After a little while the download fails and sometimes pgrok client crashes, not always. When it doesn't crash, memory usage stays high for a couple of minutes and then starts releasing. The scenario was conducted on a 100mbps internet connection.

Client: Kubuntu 20.04 Linux 5.8 amd64

**Comment by jerson** [comment]
I never tested with file download, it should be as the initial implementation of ngrok, I think a debug is needed to correct this error, thanks for report the issue

**Comment by dinccey** [comment]
There seems to be a fix for the original ngrok: #3463565536ab417d7c0a1d4b6cf5a073c128f944
https://github.com/xinxin8816/ngrok/commit/3463565536ab417d7c0a1d4b6cf5a073c128f944

**Comment by dinccey** [comment]
Whoa you're fast! Thanks for that, I'll test it now.
