### ISSUE TITLE
server_addr is ignored in ~/.pgrok config

### ISSUE THREAD

**Issue by synchrone** [jerson/pgrok#7]
in https://github.com/jerson/pgrok/blob/master/client/config.go#L83 `if opts.serveraddr != "" {` is always true, because https://github.com/jerson/pgrok/blob/master/client/cli.go#L121 has defaultServerAddr set.

Hence, no matter what's written in `~/.pgrok` as `server_addr` - it will be ignored.

**Comment by jerson** [comment]
mmm thats true, my bad i will replace this on my next commits or maybe if you have some time you can help me with the PR, thanks for report the issue

**Comment by michaljaz** [comment]
@jerson, I fixed it

**Comment by jerson** [comment]
https://github.com/jerson/pgrok/releases/tag/v3.2.5
