### ISSUE TITLE
Is there any way to make only 1 port active for TCP?

### ISSUE THREAD

**Issue by BBCLSD** [jerson/pgrok#9]
Help please, I configured the TCP server for port 1, but after activating this program, the port changed on the second computer, and after restarting on the first computer, the port became the same as on the second, is it possible to reserve one port so that it does not change?

**Comment by jerson** [comment]
hi @BBCLSD thanks for report the issue, sorry pgrok doesnt support reserved port, maybe you want to take a look at this
https://github.com/fatedier/frp

this is a library to use a fixed port

**Comment by BBCLSD** [comment]
I’m very stupid, and I don’t really understand such software, I even downloaded your source code, plus I downloaded Goland, but my brains are not even enough to compile, so could you help me with this program, mentioned above "FRP". I have Windows 8.1, I ask for your help, Help for God's sake! I will be very grateful. There is no money yet, but as soon as they appear, I will not forget about you!

**Comment by jerson** [comment]
hi @BBCLSD  frp needs a server to make it work, but as i mentioned before sadly we dont support fixed port for  tcp, I wish I could help you, but you may need a paid service like the one offered by ngrok https://ngrok.com/pricing.

**Comment by programmeruser2** [comment]
@BBCLSD you have to self-host FRP, there's no demo instance.

**Comment by programmeruser2** [comment]
Perhaps there could be a interface to request a static port? Maybe
```shell
pgrok --request-port 22000
```
